# Generated by Django 4.1.6 on 2023-02-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heartML", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(name="Person",),
    ]
