# Generated by Django 4.1.6 on 2023-02-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heartML", "0002_topic_delete_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.IntegerField()),
                ("bmi", models.IntegerField()),
                ("smoking", models.IntegerField()),
                ("alcohol", models.IntegerField()),
                ("stroke", models.IntegerField()),
                ("phealth", models.IntegerField()),
                ("mhealth", models.IntegerField()),
                ("diffwalking", models.IntegerField()),
                ("age", models.IntegerField()),
                ("race", models.IntegerField()),
                ("diabetes", models.IntegerField()),
                ("pact", models.IntegerField()),
                ("ghealth", models.IntegerField()),
                ("sleep", models.IntegerField()),
                ("asthma", models.IntegerField()),
                ("kidney", models.IntegerField()),
                ("skin", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(name="Topic",),
    ]
